### ISSUE TITLE
Readme requested

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/csl-lnum#1]
Please add a readme to indicate the purpose and organization of this repository.

Also, Github sent me an email saying `@drdhaval2785 has transferred the drdhaval2785/csl-lnum repository to sanskrit-lexicon/csl-lnum.`

How do you accomplish a 'transfer'?  Does the drdhaval2785/csl-lnum go away?

**Comment by drdhaval2785** [comment]
1. Readme. I will not write a readme until you write a readme for csl-orig. See https://github.com/sanskrit-lexicon/csl-orig/issues/603 . (Just kidding. Will write a readme soon.)
2.  For transferring a repository, you enter the 'danger zone' at the bottom of this page. https://github.com/sanskrit-lexicon/csl-lnum/settings . It requires you to enter your password etc. Yes, the drdhaval2785/csl-lnum does go away. But it seems that github does some sort of redirecting. If I type https://github.com/drdhaval2785/csl-lnum/ in the browser and hit enter, I land on https://github.com/sanskrit-lexicon/csl-lnum. That is kind of good. You do not want your old users to be unhappy if they land on your page and find 404.

**Comment by funderburkjim** [comment]
Ok. Thanks for info.  Also thanks for gentle reminder.

**Comment by drdhaval2785** [comment]
Readme has been written, in case you have not read yet.

**Comment by funderburkjim** [comment]
Have read readme.  Thanks.
